### ISSUE TITLE
Problems with Calibration/ server.js

### ISSUE THREAD

**Issue by Quaspiel** [pylapp/tapsterbot#3]
In the Wiki to this GitHub a bot.js is mentioned, is this missing or is it a reference to the bot.js in the Legacy Tapster GitHub?
Do I have to integrate the files from this GitHub Page into the Files from the Legacy-GitHub to get it running?

If I try to run server.js after `npm install ` it gives me the following error:
`UnhandledPromiseRejectionWarning: TypeError: SerialPort.list no longer takes a callback and only returns a promise`

What am I doing wrong?

**Comment by michallaskowski** [comment]
You are using probably a newer version of node. There was quite a big change between node 12 and 13, where they changed quite a lot around asynchronous methods. I am using 11.15.0. I think I had similar issues with node 13.x.x

**Comment by Quaspiel** [comment]
Using 11.15.0 now and it fixed it.
Thank you very much.
