### ISSUE TITLE
Appium Issues

### ISSUE THREAD

**Issue by Quaspiel** [pylapp/tapsterbot#4]
appium --pre-launch --default-capabilities '
{>>     "app": "C:/Users/Quaspiel/Desktop/tapsterbot-dev/tapsterbot-dev/calibration/android/calibration-android.apk",
     "platformName": "Android",
     "platformVersion": "8.0.0",
     "deviceName": "GalaxyS7",
     "autoLaunch": "true",
     "appPackage": "pylapp.tapster.calibration.android",
     "appActivity": "pylapp.tapster.calibration.android.MainActivity"
   }'

Doesn't seem to work for me.

It just always puts out 
`C:\Program Files\nodejs\node_modules\appium\build\lib\main.js: error: argument "-dc/--default-capabilities": Invalid parseDefaultCaps value: {`

Do I need to use a previous Appium-Version or what is the issue here?

**Comment by Quaspiel** [comment]
Got it to at least output everything:

C:\Program Files\nodejs\node_modules\appium\build\lib\main.js: error: argument "-dc/--default-capabilities": Invalid parseDefaultCaps value: {
    app: C:/Users/Quaspiel/Desktop/tapsterbot-dev/tapsterbot-dev/calibration/android/calibration-android.apk,
    platformName: Android,
    platformVersion: 8.0.0,
    deviceName: GalaxyS7,
    autoLaunch: true,
    appPackage: pylapp.tapster.calibration.android,
    appActivity: pylapp.tapster.calibration.android.MainActivity
  }

**Comment by pylapp** [comment]
Hi,

Maybe you need to use an older version of Appium, or make an upgrade of the existing scripts to use a newer version.

The last time I worked on this project, I used Appium 1.4.

Feel free to have a look on this page of the wiki: https://github.com/pylapp/tapsterbot/wiki/12--%5C-More-technical-details
